# Fachreza Riyanda (202131116) - Naive Bayes

## Import Library

In [34]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report


## Membaca dan Menampilkan Data

In [38]:
data = pd.read_excel("data_kramik.xlsx")
data

No Data Jenis Barang     Merk   Harga        Kelas
0         1       Kramik  Vicenza  385500        Laris
1         2       Kramik  Vicenza  538500        Laris
2         3       Kramik  Vicenza  538500        Laris
3         4      Plastik  Sunlife   18300        Laris
4         5      Plastik  Sunlife   12500        Laris
5         6      Plastik     Fori   27500        Laris
6         7         Kaca  Vicenza  520000        Laris
7         8         Kaca  Sunlife  179000  Tidak Laris
8         9       Kramik  Sunlife  178000        Laris
9        10       Kramik  Vicenza   44500        Laris
10       11         Kaca  Vicenza  600000        Laris
11       12         Kaca  Sunlife  285000  Tidak Laris
12       13         Kaca  Sunlife  329000  Tidak Laris
13       14         Kaca  Vicenza  415000        Laris
14       15       Kramik  Vicenza  309000        Laris
15       16       Kramik  Vicenza  865000        Laris
16       17       Kramik     Fori  999000        Laris
17       18      Plastik     Fori  339000        Laris
18       19      Plastik     Fori  289000        Laris
19       20      Plastik     Fori  559500        Laris

## Pre-Processing Data

In [39]:
from sklearn.preprocessing import LabelEncoder

for col in ['Jenis Barang', 'Merk', 'Kelas']:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col])

print(data['Jenis Barang'].unique(), data['Merk'].unique(), data['Kelas'].unique())

[1 2 0] [2 1 0] [0 1]


In [40]:
x = np.asarray(data.drop(['No Data', 'Kelas'], axis=1))
y = np.asarray (data['Kelas'])

In [41]:
data

No Data  Jenis Barang  Merk   Harga  Kelas
0         1             1     2  385500      0
1         2             1     2  538500      0
2         3             1     2  538500      0
3         4             2     1   18300      0
4         5             2     1   12500      0
5         6             2     0   27500      0
6         7             0     2  520000      0
7         8             0     1  179000      1
8         9             1     1  178000      0
9        10             1     2   44500      0
10       11             0     2  600000      0
11       12             0     1  285000      1
12       13             0     1  329000      1
13       14             0     2  415000      0
14       15             1     2  309000      0
15       16             1     2  865000      0
16       17             1     0  999000      0
17       18             2     0  339000      0
18       19             2     0  289000      0
19       20             2     0  559500      0

## Split Data

In [42]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

## Model Naive Bayes 

In [43]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

model = GaussianNB()
model.fit (x_train, y_train)

GaussianNB()

In [44]:
y_pred = model.predict(x_test)
y_pred

array([1, 0, 0, 0])

## Model Evaluasi 

In [45]:
from sklearn.metrics import accuracy_score
print("Naive Bayes Accuracy: ", accuracy_score(y_test, y_pred))

Naive Bayes Accuracy:  0.75


In [48]:
new_data = [[0, 0, 44000]]

In [49]:
new_pred = model.predict(new_data)
new_pred

array([0])